### ISSUE TITLE
Asking for suggestion

### ISSUE THREAD

**Issue by denniscual** [siro47/CornerCleanArchitectureNode#1]
You're article is really great and this repository gives me some insight about Clean architecture. I recently read the Clean architecture book and I'm searching some sample projects in node.js which use the architecture then I find your awesome repo. 

Based on Clean architecture, we need to define some Interface adapter to communicate the infrastructure to use case layer. Javascript doesn't have Interface, so how do you separate the interface to its implementation in Javascript? How about port and adapter, how do you deal with it? 

And also how do you define the entity? I would love to hear your suggestion.

**Comment by siro47** [comment]
Answered in the related article:
https://solidgeargroup.com/clean-architecture-in-nodejs
