### ISSUE TITLE
Detected: Promise anti pattern 

### ISSUE THREAD

**Issue by charliemc** [siro47/CornerCleanArchitectureNode#2]
Hi there,

First of all, 🎉congratulations🎉: such a nice article you wrote, thank you both for the effort put on it and for sharing your approach! 🙂

I was reading through it meanwhile following the code, and found out that there are some parts where you are dealing with promises / promise chaining that could be simplified even more: you are following an anti pattern that is adding some unnecessary complexity to your code. 

Every time you start or follow a promise chain, you tend to create and return a new Promise (`new Promise(function(resolve, reject) {})`). Consider the following pieces of code:

- **/db/groups.js:**

```js
exports.getGroup = function (groupId) {
    return new Promise(function(resolve, reject) {
        Group.findOne({_id: groupId})
            .then(group => {
                resolve(group);
            })
            .catch(err => {
                console.log("Error retrieving groups: " + err);
                reject(err);
            })
    })
}
```

- **/domain/groups.js:**

```js
exports.getGroup = function (groupId) {
    return new Promise(function(resolve, reject) {
        groupsDB.getGroup(groupId)
            .then(group => {
                resolve(group);
            })
            .catch(err => {
                reject(err);
            })
    });
}
```

These, could be straightforward simplified to the following (and the behavior would stay the same):

- **/db/groups.js:**

```js
exports.getGroup = function (groupId) {
    return Group.findOne({_id: groupId});
}
```

- **/domain/groups.js:**

```js
exports.getGroup = function (groupId) {
    return groupsDB.getGroup(groupId);
}
```

That way, you could have this unnecessary complexity removed from your source code and it would even look much cleaner! 👌 

In this case, as Mongoose calls return a Promise theirselves already, there is no need from your side to create one by wrapping your functions inside `new Promise(...)` statements: the promise chain already started, you could just return that promise straightforward, and do some chaining from the outside.

You will be able to find more information about this anti pattern in the following links:

- https://stackoverflow.com/a/35945611/3023947
- https://stackoverflow.com/questions/23803743/what-is-the-explicit-promise-construction-antipattern-and-how-do-i-%20avoid-it
- https://github.com/petkaantonov/bluebird/wiki/Promise-Anti-patterns#the-deferred-anti-pattern
- https://runnable.com/blog/common-promise-anti-patterns-and-how-to-avoid-them

I hope I was useful in here! 😊

**Comment by siro47** [comment]
Hi Charlie,

you're totally right! Sadly there are some parts of code that are a bit old and need a rewriting. Probably I'll even try to move everything to the new async/await specification.

I'll keep this issue open until I find the time to apply those modifications. Hope it'll be soon 🤞 

Thank you very much for your feedback, Charlie. Very much appreciated 😄

**Comment by charliemc** [comment]
You are very welcome, Siro. Looking forward to seeing the `async/await` in place! 😀

**Comment by siro47** [comment]
New code updated using async/await 🎉 
Therefore I'm closing this.
